import { StyleSheet } from 'react-native';

const wineDetailStyle = StyleSheet.create({
  mainBackground: {
    flex: 1,
    backgroundColor: '#f8f1e9',
    minHeight: '100%',
  },
  card: {
    backgroundColor: '#fff',
    marginTop: 0,
    paddingHorizontal: 20,
    paddingVertical: 24,
    width: '100%',
    alignSelf: 'stretch',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    zIndex: 2,
  },
  imageContainer: {
    backgroundColor: '#f8f1e9',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingTop: 32,
    paddingBottom: 32,
    alignItems: 'center',
    width: '100%',
    position: 'relative',
  },
  imageCircle: {
    position: 'absolute',
    top: 24,
    left: '50%',
    marginLeft: -120,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#f3e6e1',
    zIndex: 1,
  },
  image: {
    width: 220,
    height: 320,
    borderRadius: 18,
    alignSelf: 'center',
    marginBottom: 0,
    zIndex: 2,
    marginTop: 24,
  },
  name: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#61142b',
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 2,
  },
  region: {
    fontSize: 15,
    color: '#8B2D3E',
    textAlign: 'center',
    marginBottom: 2,
  },
  producer: {
    fontSize: 13,
    color: '#888',
    textAlign: 'center',
    marginBottom: 10,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  rating: {
    fontSize: 18,
    color: '#F4B400',
    marginLeft: 8,
    fontWeight: 'bold',
  },
  tagsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3e6e1',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginHorizontal: 2,
    marginVertical: 2,
    gap: 4,
  },
  tagText: {
    fontSize: 13,
    color: '#61142b',
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: '#f0e6e6',
    marginVertical: 16,
    width: '100%',
    alignSelf: 'center',
  },
  section: {
    width: '100%',
    marginBottom: 18,
  },
  sectionTitle: {
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 4,
    color: '#61142b',
  },
  sectionText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 2,
  },
  harmonizationSection: {
    backgroundColor: '#f8f1e9',
    borderRadius: 14,
    padding: 12,
    marginTop: 4,
  },
  harmonizationItem: {
    fontSize: 14,
    color: '#61142b',
    marginLeft: 8,
    marginBottom: 2,
  },
  actionButton: {
    backgroundColor: '#61142b',
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 30,
    width: '100%',
    alignSelf: 'center',
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1,
  },
  countryChip: {
    position: 'absolute',
    top: 18,
    left: '50%',
    transform: [{ translateX: -50 }],
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#f3e6e1',
    zIndex: 3,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  countryChipText: {
    color: '#61142b',
    fontWeight: 'bold',
    fontSize: 13,
  },
  nameOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.85)',
    paddingVertical: 10,
    alignItems: 'center',
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    zIndex: 3,
  },
  nameOverlayText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#61142b',
    textAlign: 'center',
  },
  ratingCircleContainer: {
    alignItems: 'center',
    marginTop: -40,
    marginBottom: 16,
    zIndex: 3,
  },
  ratingCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#61142b',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  ratingValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  starsRow: {
    flexDirection: 'row',
    marginTop: 6,
    marginBottom: 2,
    justifyContent: 'center',
  },
  ratingCount: {
    marginTop: 8,
    fontSize: 13,
    color: '#888',
    textAlign: 'center',
  },
});

export default wineDetailStyle;